# -------------------------------------------------------------------------------------------------
# robotworker
# -------------------------------------------------------------------------------------------------
# properties
# ---------------------------------------------------------------------------
host: '127.0.0.1'
port: 20000
# ---------------------------------------------------------------------------
# sequences
# ---------------------------------------------------------------------------
sequences:
  startup:
    sequence:
      get_context : []

# -------------------------------------------------------------------------------------------------
# services
# -------------------------------------------------------------------------------------------------
services:
  # ---------------------------------------------------------------------------
  # server 1
  # ---------------------------------------------------------------------------
  server:
    cmd : 'robot_worker'
    host: '127.0.0.1'
    port: 20001
    settings:
      conf : ''
# -------------------------------------------------------------------------------------------------
# end
# -------------------------------------------------------------------------------------------------